/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plan_rutas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AndresD
 */
public class rutas extends javax.swing.JFrame {

    /**
     * Creates new form rutas
     */
    public rutas() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtOrigen = new javax.swing.JTextField();
        TxtDestino = new javax.swing.JTextField();
        TxtFecha = new javax.swing.JTextField();
        TxtHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        btn_cont = new javax.swing.JButton();
        btn_elimi = new javax.swing.JButton();
        btn_act = new javax.swing.JButton();
        btn_prin = new javax.swing.JButton();
        btn_ant1 = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        btn_fin = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 340, 40));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hora");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No.bus");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No.Conductor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Destino");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Origen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva ruta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        jPanel1.add(TxtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 190, -1));
        jPanel1.add(TxtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, -1));
        jPanel1.add(TxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 190, -1));
        jPanel1.add(TxtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 190, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.Rutas", "Origen", "Destino", "Conductor", "Empleado", "No.bus", "Fecha", "Hora"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 600, 260));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel10.setText("Historial de rutas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 150, 30));

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("No.Empleado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 110, 20));
        jPanel1.add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 190, -1));

        btn_cont.setText("Contar");
        btn_cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 80, -1));

        btn_elimi.setText("Eliminar");
        btn_elimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_elimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        btn_act.setText("Actualizar");
        btn_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actActionPerformed(evt);
            }
        });
        jPanel1.add(btn_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        btn_prin.setText("Principio");
        btn_prin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prinActionPerformed(evt);
            }
        });
        jPanel1.add(btn_prin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 90, -1));

        btn_ant1.setText("Ant.");
        btn_ant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ant1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, -1, -1));

        btn_sig.setText("Sig.");
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        btn_fin.setText("Fin.");
        btn_fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finActionPerformed(evt);
            }
        });
        jPanel1.add(btn_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No-conductor", "00023 - Carlos", "00042- Miguel" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 190, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No-bus", "4352", "2314", "2441" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_tricar/ICONOS/Recurso 4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Variables
    ArrayList<ruta> rtList = new ArrayList();
    DefaultTableModel model;
    
    int posi=0;
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        ruta rt = new ruta();

        rt.setOrigen(TxtOrigen.getText());
        rt.setDestino(TxtDestino.getText());
 
        rt.setNoEmpleado(Integer.valueOf(txtEmpleado.getText()));

        rt.setFecha(TxtFecha.getText());
        rt.setHora(Integer.valueOf(TxtHora.getText()));
        
        rtList.add(rt);  

        TxtOrigen.setText("");
        TxtDestino.setText("");
        txtEmpleado.setText("");
        TxtFecha.setText("");
        TxtHora.setText("");
        
        JOptionPane.showMessageDialog(this, "Registro realizado correctamente");
        
        PresentarTabla();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int Slt=this.jTable1.getSelectedRow();
        
        TxtOrigen.setText(rtList.get(Slt).getOrigen());
        TxtDestino.setText(rtList.get(Slt).getDestino());
        txtEmpleado.setText(String.valueOf(rtList.get(Slt).getNoEmpleado()));
        TxtFecha.setText(rtList.get(Slt).getFecha());
        TxtHora.setText(String.valueOf(rtList.get(Slt).getHora()));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contActionPerformed
       JOptionPane.showMessageDialog(this, rtList.size());
    }//GEN-LAST:event_btn_contActionPerformed

    private void btn_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actActionPerformed
        int tabla=this.jTable1.getSelectedRow();
    
        rtList.get(tabla).setOrigen(this.TxtOrigen.getText());
        rtList.get(tabla).setDestino(this.TxtDestino.getText());

        rtList.get(tabla).setNoEmpleado(Integer.valueOf(this.txtEmpleado.getText()));
        
        rtList.get(tabla).setFecha(this.TxtFecha.getText());
        rtList.get(tabla).setHora(Integer.valueOf(this.TxtHora.getText()));
        

        model.setValueAt(this.TxtOrigen.getText(),tabla,1);
        model.setValueAt(this.TxtDestino.getText(), tabla, 2);

        model.setValueAt(this.txtEmpleado.getText(),tabla,4);
        
        model.setValueAt(this.TxtFecha.getText(),tabla,6);
        model.setValueAt(this.TxtHora.getText(),tabla,7);
    }//GEN-LAST:event_btn_actActionPerformed

    private void btn_elimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimiActionPerformed
        int tabla=this.jTable1.getSelectedRow(); 
       if (tabla<0){
            JOptionPane.showMessageDialog(null, "Debe de seleccionar una fila de la tabla");

        }else {

            int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar esta fila");
            if (JOptionPane.OK_OPTION==confirmar){

                model.removeRow(tabla);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        }
         TxtOrigen.setText("");
        TxtDestino.setText("");

        txtEmpleado.setText("");
        TxtFecha.setText("");
        TxtHora.setText("");
    }//GEN-LAST:event_btn_elimiActionPerformed

    private void btn_prinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prinActionPerformed
       posi--;
        if(posi<=0){
            posi=0;
        }
        presentar(posi);
    }//GEN-LAST:event_btn_prinActionPerformed

    private void btn_ant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ant1ActionPerformed
        posi--;
        if(posi<=0){
            posi=0;
        }
        presentar(posi);  
    }//GEN-LAST:event_btn_ant1ActionPerformed

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed
        posi++;
        if(posi>=rtList.size()){
            posi=rtList.size()-1;
        }
        presentar(posi);  
    }//GEN-LAST:event_btn_sigActionPerformed

    private void btn_finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finActionPerformed
         presentar(rtList.size()-1);
         posi=rtList.size()-1;
    }//GEN-LAST:event_btn_finActionPerformed
   void presentar(int i){
    if(i>=0 && i<rtList.size()){
        
        this.TxtOrigen.setText(rtList.get(i).getOrigen());
        this.TxtDestino.setText(rtList.get(i).getDestino());
       
        this.txtEmpleado.setText(String.valueOf(rtList.get(i).getNoEmpleado()));
        this.TxtFecha.setText(rtList.get(i).getFecha());
        this.TxtHora.setText(String.valueOf(rtList.get(i).getHora())); 
        
    }
    }
    private void PresentarTabla(){
       model.setRowCount(0); 
       for(int i=0; i<rtList.size(); i++){
       model.addRow(new Object[]{rtList.get(i).getNoRuta(), rtList.get(i).getOrigen(), rtList.get(i).getDestino(),
                                 rtList.get(i).getNoConductor(),rtList.get(i).getNoEmpleado() ,rtList.get(i).getNoBus(), 
                                 rtList.get(i).getFecha(), rtList.get(i).getHora()});
   
        }

    }
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rutas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDestino;
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtHora;
    private javax.swing.JTextField TxtOrigen;
    private javax.swing.JButton btn_act;
    private javax.swing.JButton btn_ant1;
    private javax.swing.JButton btn_cont;
    private javax.swing.JButton btn_elimi;
    private javax.swing.JButton btn_fin;
    private javax.swing.JButton btn_prin;
    private javax.swing.JButton btn_sig;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmpleado;
    // End of variables declaration//GEN-END:variables
}
