/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registro_empleado;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rachel
 */

public class Registro_EMP extends javax.swing.JFrame {

    /**
     * Creates new form Registro_EMP
     */
    public Registro_EMP() {
        initComponents();
        setLocationRelativeTo(null);
        emple=(DefaultTableModel) jTable1.getModel(); 
    }
     ArrayList<Empleados> arr= new ArrayList(); 
    DefaultTableModel emple; 
    
    int posi=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNomb = new javax.swing.JTextField();
        comboEmp = new javax.swing.JComboBox<>();
        btn_agre = new javax.swing.JButton();
        btn_elimi = new javax.swing.JButton();
        btn_prin = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        btn_ant1 = new javax.swing.JButton();
        btn_fin = new javax.swing.JButton();
        btn_act = new javax.swing.JButton();
        btn_cont = new javax.swing.JButton();
        btn_cerr = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        ComBoxGen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Edad", "Género", "Num Bus", "Empleado", "Num Empleado", "Num Ruta"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 590, 340));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo Empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 50));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Empleado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));
        jPanel1.add(txtNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, -1));

        comboEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Empleado", "Conductor", "Asistente de viaje" }));
        jPanel1.add(comboEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 180, -1));

        btn_agre.setText("Agregar");
        btn_agre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agreActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 290, -1));

        btn_elimi.setText("Eliminar");
        btn_elimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_elimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        btn_prin.setText("Principio");
        btn_prin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prinActionPerformed(evt);
            }
        });
        jPanel1.add(btn_prin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        btn_sig.setText("Sig");
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, -1, -1));

        btn_ant1.setText("Ant");
        btn_ant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ant1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, -1));

        btn_fin.setText("Fin");
        btn_fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finActionPerformed(evt);
            }
        });
        jPanel1.add(btn_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, -1, -1));

        btn_act.setText("Actualizar");
        btn_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actActionPerformed(evt);
            }
        });
        jPanel1.add(btn_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 80, -1));

        btn_cont.setText("Contar");
        btn_cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 80, -1));

        btn_cerr.setText("Cerrar");
        btn_cerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 290, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Género");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 180, -1));

        ComBoxGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Género", "Femenino", "Masculino", "Otro" }));
        jPanel1.add(ComBoxGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_tricar/ICONOS/Recurso 4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agreActionPerformed
        Empleados dat= new Empleados(); 
        dat.setId(Integer.valueOf(this.txtId.getText()));
        dat.setNombre(this.txtNomb.getText());
        dat.setEdad(Integer.valueOf(this.txtEdad.getText())); 
        dat.setGenero(this.ComBoxGen.getSelectedItem().toString());
        dat.setEmpleado(this.comboEmp.getSelectedItem().toString());
       
        arr.add(dat); 
        limpiar(); 
        posi=arr.size(); 
        JOptionPane.showMessageDialog(this, "Registro realizado correctamente");
         pres_table(); 
    }//GEN-LAST:event_btn_agreActionPerformed

    private void btn_elimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimiActionPerformed
       int tabla=this.jTable1.getSelectedRow(); 
       if (tabla<0){
            JOptionPane.showMessageDialog(null, "Debe de seleccionar una fila de la tabla");

        }else {

            int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar esta fila");
            if (JOptionPane.OK_OPTION==confirmar){

                emple.removeRow(tabla);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        }
        
        limpiar(); 
    }//GEN-LAST:event_btn_elimiActionPerformed

    private void btn_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actActionPerformed
          int tabla=this.jTable1.getSelectedRow();
        arr.get(tabla).setId(Integer.valueOf(this.txtId.getText()));
        arr.get(tabla).setNombre(this.txtNomb.getText());
        arr.get(tabla).setEdad(Integer.valueOf(this.txtEdad.getText()));
        arr.get(tabla).setGenero(this.ComBoxGen.getSelectedItem().toString());
        arr.get(tabla).setEmpleado(this.comboEmp.getSelectedItem().toString());
  
        emple.setValueAt(this.txtId.getText(),tabla,0);
        emple.setValueAt(this.txtNomb.getText(),tabla,1);
        emple.setValueAt(this.txtEdad.getText(), tabla, 2);
        emple.setValueAt(this.comboEmp.getSelectedItem(),tabla,3);

        emple.setValueAt(this.comboEmp.getSelectedItem(),tabla,5);
 
    }//GEN-LAST:event_btn_actActionPerformed

    private void btn_contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contActionPerformed
        JOptionPane.showMessageDialog(this, arr.size());
    }//GEN-LAST:event_btn_contActionPerformed

    private void btn_cerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrActionPerformed
          System.exit(0);
    }//GEN-LAST:event_btn_cerrActionPerformed

    private void btn_prinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prinActionPerformed
         posi--;
        if(posi<=0){
            posi=0;
        }
        pres_datos(posi);
    }//GEN-LAST:event_btn_prinActionPerformed

    private void btn_ant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ant1ActionPerformed
         posi--;
        if(posi<=0){
            posi=0;
        }
        pres_datos(posi);  
    }//GEN-LAST:event_btn_ant1ActionPerformed

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed
         posi++;
        if(posi>=arr.size()){
            posi=arr.size()-1;
        }
        pres_datos(posi);  
    }//GEN-LAST:event_btn_sigActionPerformed

    private void btn_finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finActionPerformed
          pres_datos(arr.size()-1);
         posi=arr.size()-1;
    }//GEN-LAST:event_btn_finActionPerformed
  
      void limpiar(){

    this.txtEdad.setText("");
    this.txtId.setText("");
    this.txtNomb.setText("");
   
    }
       void pres_datos(int i){
    if(i>=0 && i<arr.size()){
    this.txtId.setText(String.valueOf(arr.get(i).getId()));
    this.txtNomb.setText(arr.get(i).getNombre()); 
    this.txtEdad.setText(String.valueOf(arr.get(i).getEdad()));
    this.ComBoxGen.setSelectedItem(arr.get(i).getGenero());

    this.comboEmp.setSelectedItem(arr.get(i).getEmpleado()); 
   
    
    }
    }
       
        void pres_table(){
   emple.setRowCount(0); 
   for(int i=0; i<arr.size(); i++){
   emple.addRow(new Object[]{arr.get(i).getId(),arr.get(i).getNombre(),arr.get(i).getEdad(),arr.get(i).getGenero(),
               arr.get(i).getNum_bus(),arr.get(i).getEmpleado(),arr.get(i).getNum_empleado(),arr.get(i).getNum_ruta()});
   }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_EMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComBoxGen;
    private javax.swing.JButton btn_act;
    private javax.swing.JButton btn_agre;
    private javax.swing.JButton btn_ant1;
    private javax.swing.JButton btn_cerr;
    private javax.swing.JButton btn_cont;
    private javax.swing.JButton btn_elimi;
    private javax.swing.JButton btn_fin;
    private javax.swing.JButton btn_prin;
    private javax.swing.JButton btn_sig;
    private javax.swing.JComboBox<String> comboEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomb;
    // End of variables declaration//GEN-END:variables
}
