/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidad_buses;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rachel
 */
public class registro_buses extends javax.swing.JFrame {

    /**
     * Creates new form registro_buses
     */
    public registro_buses() {
        initComponents();
        setLocationRelativeTo(null);
        buses=(DefaultTableModel) jTable1.getModel(); 
    }
    ArrayList<buses> arr= new ArrayList(); 
    DefaultTableModel buses; 
    
    int posi=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_numbus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_año = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_color = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_numasien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_pasajeros = new javax.swing.JTextField();
        btn_prin = new javax.swing.JButton();
        btn_ant = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        btn_fin = new javax.swing.JButton();
        btn_elim = new javax.swing.JButton();
        btn_agreg = new javax.swing.JButton();
        btn_cont = new javax.swing.JButton();
        btn_cer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_mode = new javax.swing.JTextField();
        btn_act = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_carga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de Placa");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel2.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número de Bus");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel2.add(txt_numbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel2.add(txt_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        jPanel2.add(txt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 160, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Número de Asientos");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel2.add(txt_numasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 160, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capacidad de Pasajeros");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel2.add(txt_pasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 160, -1));

        btn_prin.setText("Principo");
        btn_prin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prinActionPerformed(evt);
            }
        });
        jPanel2.add(btn_prin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        btn_ant.setText("Ant.");
        btn_ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_antActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ant, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        btn_sig.setText("Sig.");
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));

        btn_fin.setText("Fin");
        btn_fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finActionPerformed(evt);
            }
        });
        jPanel2.add(btn_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        btn_elim.setText("Eliminar Registro");
        btn_elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimActionPerformed(evt);
            }
        });
        jPanel2.add(btn_elim, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        btn_agreg.setText("Agregar");
        btn_agreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 220, 40));

        btn_cont.setText("Contar");
        btn_cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 220, 40));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modelo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel2.add(txt_mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, -1));

        btn_act.setText("Actualizar");
        btn_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actActionPerformed(evt);
            }
        });
        jPanel2.add(btn_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Bus", "Num Placa", "Modelo", "Año", "Color", "Num Asientos", "Capacidad Pas", "Carga"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Capacidad de Carga");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        jPanel2.add(txt_carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 160, -1));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUSES");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 200, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_tricar/ICONOS/Recurso 4.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int tabla=this.jTable1.getSelectedRow();
        this.txt_numbus.setText(buses.getValueAt(tabla,0).toString());
        this.txt_mode.setText(buses.getValueAt(tabla,1).toString());
        this.txtPlaca.setText(buses.getValueAt(tabla,2).toString());
        this.txt_año.setText(buses.getValueAt(tabla,3).toString());
        this.txt_color.setText(buses.getValueAt(tabla,4).toString());
        this.txt_numasien.setText(buses.getValueAt(tabla,5).toString());
        this.txt_pasajeros.setText(buses.getValueAt(tabla,6).toString());
        this.txt_carga.setText(buses.getValueAt(tabla,7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actActionPerformed

        int tabla=this.jTable1.getSelectedRow();
        arr.get(tabla).setNum_bus(Integer.valueOf(this.txt_numbus.getText()));
        arr.get(tabla).setModelo(this.txt_mode.getText());
        arr.get(tabla).setPlaca(this.txtPlaca.getText());
        arr.get(tabla).setAño(Integer.valueOf(this.txt_año.getText()));
        arr.get(tabla).setColor(this.txt_color.getText());
        arr.get(tabla).setNum_asientos(Integer.valueOf(this.txt_numasien.getText()));
        arr.get(tabla).setCantidad_pasajeros(Integer.valueOf(this.txt_pasajeros.getText()));
        arr.get(tabla).setCarga(Integer.valueOf(this.txt_carga.getText()));

        buses.setValueAt(this.txt_numbus.getText(),tabla,0);
        buses.setValueAt(this.txt_mode.getText(),tabla,1);
        buses.setValueAt(this.txtPlaca.getText(),tabla,2);
        buses.setValueAt(this.txt_año.getText(),tabla,3);
        buses.setValueAt(this.txt_color.getText(),tabla,4);
        buses.setValueAt(this.txt_numasien.getText(),tabla,5);
        buses.setValueAt(this.txt_pasajeros.getText(),tabla,6);
        buses.setValueAt(this.txt_carga.getText(),tabla,7);
    }//GEN-LAST:event_btn_actActionPerformed

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerActionPerformed

    private void btn_contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contActionPerformed
        JOptionPane.showMessageDialog(this, arr.size());
    }//GEN-LAST:event_btn_contActionPerformed

    private void btn_agregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregActionPerformed
        buses dat= new buses();
        dat.setNum_bus(Integer.valueOf(this.txt_numbus.getText()));
        dat.setModelo(this.txt_mode.getText());
        dat.setPlaca(this.txtPlaca.getText());
        dat.setAño(Integer.valueOf(this.txt_año.getText()));
        dat.setColor(this.txt_color.getText());
        dat.setNum_asientos(Integer.valueOf(this.txt_numasien.getText()));
        dat.setCantidad_pasajeros(Integer.valueOf(this.txt_pasajeros.getText()));
        dat.setCarga(Integer.valueOf(this.txt_carga.getText()));

        arr.add(dat);
        limpiar();
        posi=arr.size();
        JOptionPane.showMessageDialog(this, "Registro realizado correctamente");
        pres_table();

    }//GEN-LAST:event_btn_agregActionPerformed

    private void btn_elimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimActionPerformed
        int tabla=this.jTable1.getSelectedRow();
        this.arr.remove(tabla);
        this.buses.removeRow(tabla);

        limpiar();
    }//GEN-LAST:event_btn_elimActionPerformed

    private void btn_finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finActionPerformed
        pres_datos(arr.size()-1);
        posi=arr.size()-1;
    }//GEN-LAST:event_btn_finActionPerformed

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed
        posi++;
        if(posi>=arr.size()){
            posi=arr.size()-1;
        }
        pres_datos(posi);
    }//GEN-LAST:event_btn_sigActionPerformed

    private void btn_antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_antActionPerformed
        posi--;
        if(posi<=0){
            posi=0;
        }
        pres_datos(posi);
    }//GEN-LAST:event_btn_antActionPerformed

    private void btn_prinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prinActionPerformed
        pres_datos(0);
        posi=0;
    }//GEN-LAST:event_btn_prinActionPerformed
    void limpiar(){
    this.txtPlaca.setText("");
    this.txt_año.setText("");
    this.txt_color.setText(""); 
    this.txt_numasien.setText("");
    this.txt_numbus.setText(""); 
    this.txt_pasajeros.setText(""); 
    this.txt_mode.setText(""); 
    this.txt_carga.setText("");
    }
    
    void pres_datos(int i){
    if(i>=0 && i<arr.size()){
    this.txt_numbus.setText(String.valueOf(arr.get(i).getNum_bus()));
    this.txt_mode.setText(arr.get(i).getModelo()); 
    this.txtPlaca.setText(arr.get(i).getPlaca()); 
    this.txt_año.setText(String.valueOf(arr.get(i).getAño()));
    this.txt_color.setText(arr.get(i).getColor());
    this.txt_numasien.setText(String.valueOf(arr.get(i).getNum_asientos()));
    this.txt_pasajeros.setText(String.valueOf(arr.get(i).getCantidad_pasajeros()));
    this.txt_carga.setText(String.valueOf(arr.get(i).getCarga()));
    }
    }
    
    void pres_table(){
   buses.setRowCount(0); 
   for(int i=0; i<arr.size(); i++){
   buses.addRow(new Object[]{arr.get(i).getNum_bus(),arr.get(i).getModelo(),arr.get(i).getPlaca(),arr.get(i).getAño(), arr.get(i).getColor(),
                             arr.get(i).getNum_asientos(), arr.get(i).getCantidad_pasajeros(), arr.get(i).getCarga()});
   
   }
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_buses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_act;
    private javax.swing.JButton btn_agreg;
    private javax.swing.JButton btn_ant;
    private javax.swing.JButton btn_cer;
    private javax.swing.JButton btn_cont;
    private javax.swing.JButton btn_elim;
    private javax.swing.JButton btn_fin;
    private javax.swing.JButton btn_prin;
    private javax.swing.JButton btn_sig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_carga;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_mode;
    private javax.swing.JTextField txt_numasien;
    private javax.swing.JTextField txt_numbus;
    private javax.swing.JTextField txt_pasajeros;
    // End of variables declaration//GEN-END:variables
}
